meta_product_name: "Shabbo"
meta_title: "🇮🇱 Shabbo! - The app that gives you your saturday back!"
meta_description: "Shabbo is an easy to use, all inclusive search engine that connects Israelis who want to live their life to the max during Shabbat!"
meta_image: "CoverTest.jpg" # should exist in `app/assets/images/`

