meta_product_name: "Shabbo"
meta_description: "Shabbo is the first of it's kind: An easy to use, all-inclusive search engine that connects all in Israel who want to live their life - their way - during Shabbat!"
meta_image: "CoverTest.jpg" # should exist in `app/assets/images/`
